<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SmartAccounting.Application\SmartAccounting.Application.csproj" />
    <ProjectReference Include="..\SmartAccounting.Domain\SmartAccounting.Domain.csproj" />
  </ItemGroup>
</Project>
